### ISSUE TITLE
Livebook only? 

### ISSUE THREAD

**Issue by eugkhp** [restlessronin/openai_ex#97]
### Describe the feature or improvement you're requesting

I'm not very familiar with livebook, but was wondering if this lib could be used in a phoenix app? Couldn't find anything in the docs

**Comment by restlessronin** [comment]
@eugkhp sure, there's no reason why you couldn't use it in a phoenix app. The user guide happens to be a livebook so that the documentation is always up-to-date with the library. Otherwise it's a vanilla elixir library.

There has been [some demand for more systematic error handling and reporting](https://github.com/restlessronin/openai_ex/issues/70) for the non-interactive use case. This is [work in progress](https://github.com/restlessronin/openai_ex/tree/issue-70/non-interactive-error-handling) and should be complete shortly.

**Comment by eugkhp** [comment]
Thank you! I could take a look and try to add config and docs for mix, will it be welcome?

**Comment by restlessronin** [comment]
There is already [sample config for Mix](https://github.com/restlessronin/openai_ex/blob/main/notebooks/userguide.livemd#in-a-mix-project). I'm not sure what else is needed, but if you think of something please feel free to submit it.

**Comment by restlessronin** [comment]
I have removed references to Livebook from the library description to prevent this kind of misconception in the future.

**Comment by restlessronin** [comment]
I have removed references to Livebook from the library description to prevent this kind of misconception in the future.
